/**
 * Lyric authorship record.
 *
 * This is deliberately not a detector. Whether a passage of text was written
 * by a person is not something that can be measured reliably — the published
 * classifiers for it were withdrawn for poor accuracy, and their errors fall
 * hardest on unusual phrasing, which is most of songwriting. A tool that
 * guessed would eventually tell a writer their own words were machine-made.
 *
 * The Copyright Office does not need that guess. Authorship is asserted by
 * the applicant, under penalty of perjury, and what carries weight is
 * evidence: a fixed copy of the words, fixed at a known time, demonstrably
 * belonging to this recording. That is what this produces.
 *
 * It matters most for exactly the case this system exists to serve — lyrics
 * a person wrote, set to a recording a machine generated. There the sound
 * recording must be disclaimed and the words must not be, and the two claims
 * have to be told apart in the application.
 */

export type RightsPosture = {
  /** The applicant wrote the words. */
  lyricsAuthored: boolean
  /** The recording is machine-generated in whole or part. */
  recordingGenerated: boolean
  /** The applicant composed the music (melody, harmony, structure). */
  musicAuthored: boolean
}

export type LyricRecord = {
  /** Normalised text, as fixed. */
  text: string
  lineCount: number
  wordCount: number
  /** SHA-256 of the normalised text. */
  textHash: string
  /** SHA-256 of the recording this is bound to. */
  audioHash: string
  /**
   * Hash over both, so neither can be swapped afterwards without breaking it.
   * This is what binds the words to the recording rather than to nothing.
   */
  crossHash: string
  fixedAt: string
  posture: RightsPosture
  /** What to put in the application. */
  claim: string
  disclaim: string
  eCoText: string
}

/**
 * Normalise before hashing so a record survives being re-typed.
 *
 * Trailing whitespace, blank-line runs and line endings differ between a
 * pasted lyric sheet and the same words from a text file. Without this a
 * writer's own copy would fail to match their own record.
 */
export function normaliseLyrics(raw: string): string {
  return raw
    .replace(/\r\n?/g, '\n')
    .split('\n')
    .map((line) => line.replace(/[ \t]+$/g, '').replace(/^[ \t]+/g, ''))
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim()
}

async function sha256Hex(text: string): Promise<string> {
  const bytes = new TextEncoder().encode(text)
  const digest = await crypto.subtle.digest('SHA-256', bytes)
  return Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('')
}

function draftClaim(posture: RightsPosture): { claim: string; disclaim: string; eCoText: string } {
  const claimed: string[] = []
  if (posture.lyricsAuthored) claimed.push('the lyrics')
  if (posture.musicAuthored) claimed.push('the musical composition')

  const disclaimed: string[] = []
  // Kept as a bare noun phrase: the sentence templates below supply the
  // explanatory clause, and carrying one here produced a doubled "which".
  if (posture.recordingGenerated) disclaimed.push('the sound recording as fixed')

  const join = (items: string[]) =>
    items.join(', ').replace(/, ([^,]*)$/, items.length > 1 ? ' and $1' : '$1')

  const claim = claimed.length
    ? `Original human authorship in ${join(claimed)}.`
    : 'No authorship claimed.'
  const disclaim = disclaimed.length
    ? `Applicant expressly disclaims ${join(disclaimed)}, which is machine-generated.`
    : 'No material identified for exclusion.'

  const sentences: string[] = []
  if (claimed.length) sentences.push(`Applicant claims ${join(claimed)} as original human authorship.`)
  if (disclaimed.length) {
    sentences.push(
      `Applicant expressly disclaims copyright in ${join(disclaimed)}, which was generated by an artificial intelligence system and is excluded from this claim.`,
    )
  }

  return { claim, disclaim, eCoText: sentences.join(' ') }
}

export async function recordLyrics(params: {
  raw: string
  audioHash: string
  posture: RightsPosture
  /** Injectable so a record can be rebuilt and re-verified later. */
  fixedAt?: string
}): Promise<LyricRecord> {
  const text = normaliseLyrics(params.raw)
  const textHash = await sha256Hex(text)
  const fixedAt = params.fixedAt ?? new Date().toISOString()
  // Order is fixed and documented so the cross-hash is reproducible.
  const crossHash = await sha256Hex(`${textHash}:${params.audioHash}:${fixedAt}`)

  const lines = text.split('\n').filter((l) => l.trim().length > 0)
  const words = text.split(/\s+/).filter((w) => w.length > 0)
  const { claim, disclaim, eCoText } = draftClaim(params.posture)

  return {
    text,
    lineCount: lines.length,
    wordCount: words.length,
    textHash,
    audioHash: params.audioHash,
    crossHash,
    fixedAt,
    posture: params.posture,
    claim,
    disclaim,
    eCoText,
  }
}

/** Rebuild the cross-hash from a record's own parts to prove it is intact. */
export async function verifyRecord(record: LyricRecord): Promise<boolean> {
  const textHash = await sha256Hex(normaliseLyrics(record.text))
  if (textHash !== record.textHash) return false
  const cross = await sha256Hex(`${record.textHash}:${record.audioHash}:${record.fixedAt}`)
  return cross === record.crossHash
}

/** A portable record, for filing alongside the application. */
export function toDeclarationJson(record: LyricRecord, fileName: string): string {
  return `${JSON.stringify(
    {
      work: { recording_file: fileName, recording_sha256: record.audioHash },
      lyrics: {
        sha256: record.textHash,
        fixed_at: record.fixedAt,
        lines: record.lineCount,
        words: record.wordCount,
        text: record.text,
      },
      binding: {
        cross_hash: record.crossHash,
        formula: 'sha256(lyrics_sha256 + ":" + recording_sha256 + ":" + fixed_at)',
        note: 'Binds this text to this recording. Changing either breaks the cross-hash.',
      },
      claim: {
        asserted: record.claim,
        disclaimed: record.disclaim,
        eCO_copy_paste_text: record.eCoText,
        basis: '17 U.S.C. § 409(9); U.S. Copyright Office AI disclosure guidance (2023)',
      },
      note: 'Authorship is asserted by the applicant. This record fixes what was claimed, when, and against which recording. It does not attempt to detect who wrote the text — no reliable method for that exists.',
    },
    null,
    2,
  )}\n`
}
